defaults:
    -
        scope:
            path: ""
            type: pages
        values:
            layout: default
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post

#url: http://ompl.github.io
url: http://ompl.kavrakilab.org
highlighter: rouge
exclude:
    - README
    - LICENSE